# Generated by Django 5.2.15 on 2026-06-10 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_last_purchase_date_customer_lifetime_value_and_more'),
        ('inventory', '0006_alter_product_options_alter_stockmovement_options_and_more'),
        ('sales', '0003_roles_branches_tenant'),
        ('users', '0007_branch_city_branch_email_branch_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salespayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='sale',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='loyalty_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='loyalty_points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='loyalty_points_redeemed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunSQL(
            "UPDATE sales_sale SET number = 'VEN-' || id WHERE number IS NULL OR number = '';",
            migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='sale',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_as_salesperson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='type',
            field=models.CharField(choices=[('pos', 'Punto de venta'), ('online', 'Venta online'), ('phone', 'Venta telefónica'), ('wholesale', 'Mayoreo')], default='pos', max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='returned_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='reference',
            field=models.CharField(blank=True, help_text='Número de referencia, autorización, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente de pago'), ('partially_paid', 'Parcialmente pagado'), ('paid', 'Pagado'), ('refunded', 'Reembolsado'), ('partially_refunded', 'Parcialmente reembolsado'), ('cancelled', 'Cancelado')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card_debit', 'Tarjeta débito'), ('card_credit', 'Tarjeta crédito'), ('transfer', 'Transferencia'), ('spei', 'SPEI'), ('check', 'Cheque'), ('loyalty_points', 'Puntos de fidelidad'), ('credit_note', 'Nota de crédito')], default='cash', max_length=30),
        ),
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('percentage', 'Porcentaje de ventas'), ('fixed_per_sale', 'Monto fijo por venta'), ('tiered', 'Escalonado')], default='percentage', max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=5, help_text='Porcentaje de comisión', max_digits=5)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo por venta', max_digits=10)),
                ('min_sale_amount', models.DecimalField(decimal_places=2, default=0, help_text='Venta mínima para aplicar comisión', max_digits=10)),
                ('tiers', models.JSONField(blank=True, default=list, help_text='Niveles escalonados: [{"min": 0, "percentage": 5}, ...]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='commission_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.commissionplan'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo'), ('free_shipping', 'Envío gratis'), ('free_product', 'Producto gratis')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Valor del descuento (porcentaje o monto)', max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo del pedido para aplicar', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento máximo permitido', max_digits=10, null=True)),
                ('usage_limit', models.IntegerField(default=0, help_text='Límite de usos total (0 = ilimitado)')),
                ('usage_per_customer', models.IntegerField(default=0, help_text='Límite de usos por cliente (0 = ilimitado)')),
                ('times_used', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('expired', 'Expirado'), ('inactive', 'Inactivo')], default='draft', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='coupons', to='inventory.category')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='coupons', to='inventory.product')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.coupon'),
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('points_per_peso', models.DecimalField(decimal_places=2, default=1, help_text='Puntos ganados por cada peso gastado', max_digits=10)),
                ('points_expiration_days', models.IntegerField(default=365, help_text='Días para que los puntos expiren (0 = no expiran)')),
                ('redemption_rate', models.DecimalField(decimal_places=2, default=0.01, help_text='Valor en pesos de cada punto al canjear', max_digits=10)),
                ('min_points_to_redeem', models.IntegerField(default=100, help_text='Puntos mínimos necesarios para canjear')),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_method', models.CharField(choices=[('cash', 'Efectivo'), ('card_debit', 'Tarjeta débito'), ('card_credit', 'Tarjeta crédito'), ('transfer', 'Transferencia'), ('spei', 'SPEI'), ('check', 'Cheque'), ('loyalty_points', 'Puntos de fidelidad'), ('credit_note', 'Nota de crédito')], default='cash', max_length=30)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.organization')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('period', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual'), ('custom', 'Personalizado')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_orders', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_taxes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('top_products', models.JSONField(blank=True, default=list)),
                ('top_customers', models.JSONField(blank=True, default=list)),
                ('sales_by_category', models.JSONField(blank=True, default=dict)),
                ('sales_by_branch', models.JSONField(blank=True, default=dict)),
                ('sales_by_salesperson', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.IntegerField(default=0)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('total_points_redeemed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='crm.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='sales.loyaltyprogram')),
            ],
            options={
                'unique_together': {('customer', 'program', 'organization')},
            },
        ),
    ]
