# Generated by Django 5.2.15 on 2026-06-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salespayment_options_sale_commission_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
