# Generated by Django 5.2.15 on 2026-06-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_indexes'),
        ('sales', '0005_alter_sale_number'),
    ]

    operations = [
    ]
