# Generated by Django 5.2.15 on 2026-06-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_order_options_alter_shipment_options_and_more'),
        ('sales', '0006_merge_0002_add_indexes_0005_alter_sale_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='sale_org_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sale_branch_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleitem',
            name='saleitem_sale_product_idx',
        ),
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='logistics.order'),
        ),
    ]
