# Generated by Django 5.2.15 on 2026-06-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('inventory', '0004_roles_branches_tenant'),
        ('sales', '0003_roles_branches_tenant'),
        ('users', '0006_userinvitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='cfdi_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('stamped', 'Timbrada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='folio',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoice',
            name='forma_pago',
            field=models.CharField(default='01', max_length=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='metodo_pago',
            field=models.CharField(default='PUE', max_length=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='serie',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stamped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tipo_comprobante',
            field=models.CharField(default='I', max_length=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='uso_cfdi',
            field=models.CharField(default='G03', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='xml_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cfdi_uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('stamped', 'Timbrada'), ('sent', 'Enviada'), ('paid', 'Pagada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='draft', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('organization', 'number')},
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('clave_prod_serv', models.CharField(default='01010101', max_length=20)),
                ('clave_unidad', models.CharField(default='H87', max_length=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
