# Generated by Django 5.2.15 on 2026-06-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense_is_recurring_expense_receipt_and_more'),
        ('sales', '0006_merge_0002_add_indexes_0005_alter_sale_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='sales.sale'),
        ),
    ]
