# Generated by Django 5.2.15 on 2026-06-21 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_order_options_alter_shipment_options_and_more'),
        ('users', '0009_remove_branch_branch_org_active_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre o identificador del vehículo', max_length=255)),
                ('plate', models.CharField(help_text='Placa del vehículo', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('truck', 'Camión'), ('van', 'Camioneta'), ('motorcycle', 'Motocicleta'), ('bike', 'Bicicleta'), ('other', 'Otro')], default='truck', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('in_use', 'En uso'), ('maintenance', 'Mantenimiento'), ('out_of_service', 'Fuera de servicio')], default='available', max_length=50)),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad en kilogramos', max_digits=10, null=True)),
                ('capacity_volume', models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad en metros cúbicos', max_digits=10, null=True)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=255)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='logistics.vehicle'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='logistics.vehicle'),
        ),
    ]
