# Generated by Django 5.2.15 on 2026-06-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_vehicle_route_vehicle_shipment_vehicle'),
    ]

    operations = [
    ]
