# Generated by Django 5.2.15 on 2026-06-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_auto_20260620_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='routes', to='logistics.vehicle'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='shipments', to='logistics.vehicle'),
        ),
    ]