# Generated by Django 5.2.15 on 2026-06-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_indexes'),
        ('users', '0007_branch_city_branch_email_branch_state_and_more'),
    ]

    operations = [
    ]
