# Generated by Django 5.2.15 on 2026-06-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20260611_1844'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='branch',
            name='branch_org_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='membership',
            name='membership_user_org_idx',
        ),
    ]
