# Generated by Django 5.2.15 on 2026-06-10 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_barcode_category_product_category'),
        ('users', '0004_roles_branches_tenant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='users.branch'),
        ),
        migrations.AddField(
            model_name='stock',
            name='min_quantity',
            field=models.IntegerField(default=5, help_text='Stock mínimo para alertas'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Código de barras', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.CharField(blank=True, help_text='Ubicación dentro de la sucursal', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('organization', 'barcode'), ('organization', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'branch', 'organization')},
        ),
    ]
