# Generated by Django 5.2.15 on 2026-06-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_indexes'),
        ('inventory', '0006_alter_product_options_alter_stockmovement_options_and_more'),
    ]

    operations = [
    ]
