# Generated by Django 5.2.15 on 2026-06-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_merge_20260611_1844'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_org_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='stock_org_qty_idx',
        ),
    ]
