# Generated by Django 5.2.15 on 2026-06-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_add_indexes'),
        ('crm', '0003_customer_last_purchase_date_customer_lifetime_value_and_more'),
    ]

    operations = [
    ]
