# Generated by Django 5.2.15 on 2026-06-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_merge_20260611_1844'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_org_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_org_date_idx',
        ),
    ]
