# Generated by Django 5.2.15 on 2026-06-10 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_initial'),
        ('users', '0007_branch_city_branch_email_branch_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='type',
            field=models.CharField(choices=[('sales_spike', 'Pico de ventas'), ('stock_shortage', 'Falta de stock'), ('payment_delay', 'Retraso de pago'), ('expense_anomaly', 'Anomalía en gastos')], max_length=30),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='type',
            field=models.CharField(choices=[('sales', 'Ventas'), ('inventory', 'Inventario'), ('demand', 'Demanda'), ('finance', 'Finanzas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='category',
            field=models.CharField(choices=[('inventory', 'Inventario'), ('pricing', 'Precios'), ('marketing', 'Marketing'), ('operations', 'Operaciones'), ('finance', 'Finanzas')], max_length=20),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Nueva conversación', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('tool', 'Herramienta')], max_length=20)),
                ('content', models.TextField()),
                ('tool_call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_engine.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.organization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
