# Generated by Django 5.2.15 on 2026-06-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_notification_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, help_text='Enlace para ver más detalles', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('sale', 'Venta'), ('stock_alert', 'Alerta de stock'), ('lead', 'Lead'), ('opportunity', 'Oportunidad'), ('leave_request', 'Solicitud de permiso'), ('shipment', 'Envío'), ('system', 'Sistema')], default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('sms', 'SMS'), ('in_app', 'En aplicación'), ('whatsapp', 'WhatsApp')], default='in_app', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('pending', 'Pendiente'), ('queued', 'En cola'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='read', max_length=20),
        ),
    ]
