# Generated by Django 5.2.15 on 2026-06-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_link_notification_type_and_more'),
    ]

    operations = [
    ]
